Entity/User.php
<?php

namespace TheNextSoftware\CoreBundle\Entity;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Security\Core\Role\Role;
use Symfony\Component\Security\Core\User\UserInterface;


/**
 * User
 */
class User implements UserInterface, \Serializable
{
    /**
     * @var integer
     */
    private $id;

    /**
     * @var string
     */
    private $firstName;

    /**
     * @var string
     */
    private $lastName;

    /**
     * @var string
     */
    private $plainPassword;

    /**
     * @var string
     */
    private $password;

    /**
     * @var string
     */
    private $ip;

    /**
     * @var string
     *
     */
    private $email;

    /**
     * @var \DateTime
     */
    private $createdOn;

    /**
     * @var \DateTime
     */
    private $lastLogin;

    /**
     * @var boolean
     */
    private $isAdmin = FALSE;

    /**
     * @var string
     */
    private $photoUrlBase = '';

    public function __construct()
    {
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set firstName
     *
     * @param string $firstName
     *
     * @return User
     */
    public function setFirstName($firstName)
    {
        $this->firstName = $firstName;

        return $this;
    }

    /**
     * Get firstName
     *
     * @return string
     */
    public function getFirstName()
    {
        return $this->firstName;
    }

    /**
     * Set lastName
     *
     * @param string $lastName
     *
     * @return User
     */
    public function setLastName($lastName)
    {
        $this->lastName = $lastName;

        return $this;
    }

    /**
     * Get lastName
     *
     * @return string
     */
    public function getLastName()
    {
        return $this->lastName;
    }

    /**
     * Set password
     *
     * @param string $password
     *
     * @return User
     */
    public function setPassword($password)
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Get password
     *
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    public function getPlainPassword()
    {
        return $this->plainPassword;
    }

    public function setPlainPassword($password)
    {
        $this->plainPassword = $password;
    }

    /**
     * Set ip
     *
     * @param string $ip
     *
     * @return User
     */
    public function setIp($ip)
    {
        $this->ip = $ip;

        return $this;
    }

    /**
     * Get ip
     *
     * @return string
     */
    public function getIp()
    {
        return $this->ip;
    }

    /**
     * Set email
     *
     * @param string $email
     *
     * @return User
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set createdOn
     *
     * @param \DateTime $createdOn
     *
     * @return User
     */
    public function setCreatedOn($createdOn)
    {
        $this->createdOn = $createdOn;

        return $this;
    }

    /**
     * Get createdOn
     *
     * @return \DateTime
     */
    public function getCreatedOn()
    {
        return $this->createdOn;
    }

    /**
     * Set lastLogin
     *
     * @param \DateTime $lastLogin
     *
     * @return User
     */
    public function setLastLogin($lastLogin)
    {
        $this->lastLogin = $lastLogin;

        return $this;
    }

    /**
     * Get lastLogin
     *
     * @return \DateTime
     */
    public function getLastLogin()
    {
        return $this->lastLogin;
    }

    /**
     * Returns the roles granted to the user.
     *
     * <code>
     * public function getRoles()
     * {
     *     return array('ROLE_USER');
     * }
     * </code>
     *
     * Alternatively, the roles might be stored on a ``roles`` property,
     * and populated in any number of different ways when the user object
     * is created.
     *
     * @return Role[] The user roles
     */
    public function getRoles()
    {
        if($this->getIsAdmin())
        {
            return [ 'ROLE_USER', 'ROLE_ADMIN' ];
        }else{
            return [ 'ROLE_USER' ];
        }
    }

    /**
     * Returns the salt that was originally used to encode the password.
     *
     * This can return null if the password was not encoded using a salt.
     *
     * @return string|null The salt
     */
    public function getSalt()
    {
        return NULL;
    }

    /**
     * Returns the username used to authenticate the user.
     *
     * @return string The username
     */
    public function getUsername()
    {
        return $this->email;
    }

    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials()
    {
    }

    /** @see \Serializable::serialize() */
    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->email,
            $this->password,
            $this->createdOn,
            $this->lastLogin,
            $this->firstName,
            $this->lastName,
            $this->isAdmin
        ));
    }

    /** @see \Serializable::unserialize() */
    public function unserialize($serialized)
    {
        list (
            $this->id,
            $this->email,
            $this->password,
            $this->createdOn,
            $this->lastLogin,
            $this->firstName,
            $this->lastName,
            $this->isAdmin
            ) = unserialize($serialized);
    }

    /**
     * Get restaurants
     *
     * @return \Doctrine\Common\Collections\ArrayCollection
     */
    public function getCompanies()
    {
        return new ArrayCollection(array_merge($this->getOwnedCompanies()->toArray(), $this->getCompanyRoles()->map(function ($role) {
            /** @var $role UserRole */
            return $role->getCompany();
        })->toArray()));
    }

    /**
     * Sets created_at to the current date.
     */
    public function updateCreatedOn()
    {
        $this->setCreatedOn(new \DateTime());
    }

    /**
     * Sets created_at to the current date.
     */
    public function updateLastLogin()
    {
        $this->setLastLogin(new \DateTime());
    }

    public function __toString()
    {
        return $this->getEmail();
    }


    /**
     * Set isAdmin
     *
     * @param boolean $isAdmin
     *
     * @return User
     */
    public function setIsAdmin($isAdmin)
    {
        $this->isAdmin = $isAdmin;

        return $this;
    }

    /**
     * Get isAdmin
     *
     * @return boolean
     */
    public function getIsAdmin()
    {
        return $this->isAdmin;
    }

    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $ownedCompanies;

    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $companyRoles;

    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $userPhotos;


    /**
     * Add ownedCompany
     *
     * @param Company $ownedCompany
     *
     * @return User
     */
    public function addOwnedCompany(Company $ownedCompany)
    {
        $this->ownedCompanies[] = $ownedCompany;

        return $this;
    }

    /**
     * Remove ownedCompany
     *
     * @param Company $ownedCompany
     */
    public function removeOwnedCompany(Company $ownedCompany)
    {
        $this->ownedCompanies->removeElement($ownedCompany);
    }

    /**
     * Get ownedCompanies
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getOwnedCompanies()
    {
        return $this->ownedCompanies;
    }

    /**
     * Add companyRole
     *
     * @param UserRole $companyRole
     *
     * @return User
     */
    public function addCompanyRole(UserRole $companyRole)
    {
        $this->companyRoles[] = $companyRole;

        return $this;
    }

    /**
     * Remove companyRole
     *
     * @param UserRole $companyRole
     */
    public function removeCompanyRole(UserRole $companyRole)
    {
        $this->companyRoles->removeElement($companyRole);
    }

    /**
     * Get companyRoles
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getCompanyRoles()
    {
        return $this->companyRoles;
    }

    /**
     * Add userRole
     *
     * @param UserPhoto $userPhoto
     *
     * @return User
     */
    public function addUserPhoto(UserPhoto $userPhoto)
    {
        $this->userPhotos[] = $userPhotos;

        return $this;
    }

    /**
     * Remove userPhoto
     *
     * @param UserPhoto $userPhoto
     */
    public function removeUserPhoto(UserPhoto $userPhoto)
    {
        $this->userPhotos->removeElement($userPhoto);
    }

    /**
     * Get userPhotos
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getUserPhotos()
    {
        return $this->userPhotos;
    }

    /**
     * Get userPhoto
     *
     * @return string
     */
    public function getPhoto()
    {
        if (count($this->userPhotos) > 0) {
            return $this->userPhotos->last();
        }

        return null;
    }



    /**
     * Get userPhotoUrl
     *
     * @return string
     */
    public function getPhotoUrl()
    {
        $lastPhoto = $this->getPhoto();

        if ($lastPhoto) {
            return "{$this->getPhotoUrlBase()}{$lastPhoto->getFilename()}";
        }

        return null;
    }

    /**
     * @var string
     */
    private $activationCode;


    /**
     * Set activationCode
     *
     * @param string $activationCode
     *
     * @return User
     */

Resources/views/inc/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <title>{% block title %}Nieuw document{% endblock %}{{ title_postfix }}</title>
        {% block stylesheets %}{% endblock %}
        <link rel="icon" type="image/x-icon" href="{{ asset('favicon.ico') }}" />
    </head>
    <body {% block body_tags %} {% endblock %}>
        {% block body %}{% endblock %}

        {% block javascripts %}{% endblock %}
    </body>

    {% block after_body %}

    {% endblock %}
</html>

Resources/views/inc/base_dashboard.html.twig
{% extends '@TheNextCore/inc/inspinia_base.html.twig' %}

{% if app.request.attributes.get('_route_params')['company_id'] is defined %}
	{% set mainMenu = knp_menu_get('main', [], { company_id: app.request.attributes.get('_route_params')['company_id'] }) %}
{% else %}
	{% set mainMenu = knp_menu_get('main', [], { company_id: 1 }) %}
{% endif %}

{% block title %}
	{{ knp_menu_get_current_item(mainMenu).label }}
{% endblock %}

{% use '@TheNextCore/inc/base_dashboard_body.html.twig' %}

Resources/views/inc/base_dashboard_body.html.twig
{% use "@TheNextCore/inc/base_dashboard_body_actual.html.twig" %}

Resources/views/inc/base_dashboard_body_actual.html.twig
{% block body %}
<div id="wrapper">
    <nav class="navbar-default navbar-static-side" role="navigation">
        <div class="sidebar-collapse">
            <ul class="nav metismenu" id="side-menu">
                <li class="nav-header">
                    <div class="dropdown profile-element">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
								<span class="clear">
									<span class="block m-t-xs">
										<strong class="font-bold">{{ app.user.firstName }} {{ app.user.lastName }}</strong>
									</span>
									<span class="block m-t-xs">
										{{ app.user.email }}
									</span>
									<span class="text-muted text-xs block">
                                        {% block userstatus %}
                                            {{ "Opties"|trans }}
                                        {% endblock %}
										<b class="caret"></b>
									</span>
								</span>
                        </a>
                        <ul class="dropdown-menu animated fadeInRight m-t-xs">
                            <li><a href="{{ path("change_password") }}">Wachtwoord wijzigen</a></li>
                            <li><a href="{{ path("company_create") }}">Nieuw restaurant aanmaken</a></li>
                            <li class="divider"></li>
                            <li><a href="{{ path("logout") }}">Logout</a></li>
                        </ul>
                    </div>
                    <div class="logo-element">
                        TNR
                    </div>
                </li>

                {% set on_admin_page = app.request.attributes.get('_route')|slice(0, 5) == "admin" %}

                {% if on_admin_page %}
                    {{ knp_menu_render('admin', {
                        'currentClass': 'active',
                        'ancestorClass': 'active'
                    }) }}
                {% else %}
                    {{ knp_menu_render(mainMenu, {
                        'currentClass': 'active',
                        'ancestorClass': 'active'
                    }) }}
                {% endif %}
            </ul>
        </div>
    </nav>

    <div id="page-wrapper" class="gray-bg">
        <div class="row border-bottom">
            <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
                </div>
                {% block extra_topbar %}

                {% endblock %}
                <ul class="nav navbar-top-links navbar-right">
                    {% if is_granted('ROLE_ADMIN') %}
                        <li>
                            <a href="{{ path('admin_company_list') }}">
                                <i class="fa fa-lock"></i> Admin
                            </a>
                        </li>
                    {% endif %}
                    {% if on_admin_page or app.user.companies.count > 1 %}
                        <li>
                            <a href="{{ path('company_select') }}">
                                <i class="fa fa-list"></i> Bedrijf
                            </a>
                        </li>
                    {% endif %}
                    <li>
                        <a href="{{ path('logout') }}">
                            <i class="fa fa-sign-out"></i> Log uit
                        </a>
                    </li>
                </ul>

            </nav>
        </div>

        <div class="row wrapper border-bottom white-bg page-heading">
            {% block titlebar %}
                <div class="col-lg-10">
                    {% block titlebar_header %}
                        <h2>
                            {% block breadcrumb_title %}
                                {{ block('title') }}
                            {% endblock %}
                        </h2>

                        {% block breadcrumb %}
                            <ol class="breadcrumb">
                                {% for breadcrumb_item in knp_menu_get_breadcrumbs_array(knp_menu_get_current_item(mainMenu)) %}
                                    {% if not loop.last %}
                                        <li><a href="{{ breadcrumb_item.uri }}">{{ breadcrumb_item.label }}</a></li>
                                    {% else %}
                                        <li><strong>{{ breadcrumb_item.label }}</strong></li>
                                    {% endif %}
                                {% endfor %}
                            </ol>
                        {% endblock %}
                    {% endblock %}
                </div>
                <div class="col-lg-2">
                </div>
            {% endblock %}
        </div>

        <div class="wrapper wrapper-content">
            {% block content %}
                CONTENT
            {% endblock %}
        </div>


        <div class="footer">
            {% block footer %}

            {% endblock %}
            <div>
                <strong>Copyright</strong> {{ site_name }} &copy; 2015-2016
            </div>
        </div>

    </div>
</div>
{% endblock %}

Resources/views/inc/base_mini.html.twig
{% extends '@TheNextCore/inc/inspinia_base.html.twig' %}

{% block body_tags %}
    class="gray-bg"
{% endblock %}

{% block body %}
    <div class="middle-box text-center loginscreen animated fadeInDown"
         style="width: {% block content_width %}{% endblock %}px; max-width: {{ block('content_width') }}px; position: relative;">
        <div>
            <div>
                <img src="{{ asset(site_logo_asset) }}" style="width: 100%;"/>
            </div>
            {% block content %}

            {% endblock %}
            <p class="m-t"> <small>{{ site_name }} &copy; 2016</small> </p>
        </div>
    </div>
{% endblock %}

Resources/views/inc/inspinia_base.html.twig
{% extends '@TheNextCore/inc/inspinia_base_actual.html.twig' %}


Resources/views/inc/inspinia_base_actual.html.twig
{% extends '@TheNextCore/inc/base.html.twig' %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('assets/inspinia/css/animate.css') }}" />
    <link rel="stylesheet" href="{{ asset('assets/inspinia/css/plugins/toastr/toastr.min.css') }}" />

    <link rel="stylesheet" href="{{ asset('assets/datepicker/css/bootstrap-datepicker3.min.css') }}" />
    <link rel="stylesheet" href="{{ asset('assets/inspinia/css/bootstrap.min.css') }}" />
    <link rel="stylesheet" href="{{ asset('assets/inspinia/css/style.min.css') }}" />
    <link rel="stylesheet" href="{{ asset('assets/datepicker/css/bootstrap-datepicker.min.css') }}" />
    <link rel="stylesheet" href="{{ asset('assets/font-awesome/css/font-awesome.min.css') }}" />

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&lang=en"/>
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('assets/inspinia/js/jquery-2.1.1.js') }}"></script>
    <script src="{{ asset('assets/inspinia/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('assets/datepicker/js/bootstrap-datepicker.min.js') }}"></script>
    <script src="{{ asset('assets/datepicker/locales/bootstrap-datepicker.nl.min.js') }}"></script>
    <script src="{{ asset('assets/inspinia/js/plugins/metisMenu/jquery.metisMenu.js') }}"></script>
    <script src="{{ asset('assets/inspinia/js/plugins/slimscroll/jquery.slimscroll.js') }}"></script>
    <script src="{{ asset('assets/inspinia/js/plugins/toastr/toastr.min.js') }}"></script>
    <script src="{{ asset('assets/inspinia/js/plugins/chartJs/Chart.min.js') }}"></script>
    <script src="{{ asset('assets/inspinia/js/inspinia.js') }}"></script>
{% endblock %}

{% block after_body %}
    <script>
        toastr.options = {
            closeButton: true,
            progressBar: false,
            showMethod: 'slideDown',
            timeOut: 4000
        };

        {% for flash_message in app.session.flashbag.get('notice') %}
        toastr.success("{{ flash_message|escape("js") }}");
        {% endfor %}

        {% for flash_message in app.session.flashbag.get('warning') %}
        toastr.warning("{{ flash_message|escape("js") }}");
        {% endfor %}

        {% for flash_message in app.session.flashbag.get('error') %}
        toastr.error("{{ flash_message|escape("js") }}");
        {% endfor %}
    </script>
{% endblock %}